#Create the Secrets
apiVersion: v1
kind: Secret
metadata:
  name: user
type: Opaque
stringData: 
  username: admin
---
#Create the Secrets
apiVersion: v1
kind: Secret
metadata:
  name: pass
type: Opaque
stringData: 
  password: 1f2d1e2e67df
---
#Configure a projected volume for a pod
apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
spec:
  containers:
  - name: test-projected-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass
---
